[package]
name = "ds-nyaa"
version.workspace = true
edition.workspace = true
description = "nyaa.si BT 源（RSS 解析）"

[dependencies]
ani-core = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
feed-rs = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
smol_str = { workspace = true }
url = { workspace = true }
